<script src="../lib/fx.js"></script>

# Promise

## 일급

<script>
    function add10(a, callback) {
        setTimeout(() => callback(a + 10), 100)
    }

    add10(5, res => {
        add10(res, res=> {
            log(res)
        })
    })

    function add20(a) {
        return new Promise(resolve => setTimeout(() => resolve(a + 20), 100));
    }

    add20(5)
        .then(add20)
        .then(add20)
        .then(log);
    // 값으로 다뤄진다 => 일급
</script>

## 일급 활용

<script>
    const delay100 = a => new Promise(resolve => setTimeout(() => resolve(a), 100));

    const go1 =(a, f) => a instanceof Promise ? a.then(f) : f(a);
    const add5 = a => a + 5;

    const n1 = 10;
    go1(go1(n1, add5), log);

    const n2 = delay100(10);
    go1(go1(n2, add5), log);

</script>

## Composition

어떠한 값이 들어올지 모르는 경우,
함수 합성을 안전하게 하는 방법 => 모나드

<script type="module">
    // f . g
    // f(g(x));

    const g = a => a + 1;
    const f = a => a * a;

    log(f(g(1)));

    [1].map(g).map(f)/*.forEach(r => log(r));*/
    // [].map(g).map(f)/*.forEach(r => log(r));*/

    Array.of(1).map(g).map(f)/* .forEach(r => log(r));*/

    Promise.resolve(2).then(g).then(f)/*.then(r => log(r));*/
    new Promise(resolve =>
        setTimeout(() => resolve(2), 100)
    ).then(g).then(f)/* .then(r => log(r));*/


</script>

## Kleisli Composition

들어오는 인자가 잘못된 인자여서 함수의 에러
정확한 인자여도 외부 요인에 의한 에러
이러한 현상을 해결하기 위한 방법

<script type="module">
    // f . g
    // f(g(x)) = f(g(x))
    // 에러가 날경우 하단의 코드처럼 같은 에러를 반환하도록 하는 것 Kleisli Composition
    // x 든 g 든 에러가 발생했을때
    // f(g(x)) = g(x)

    const users = [
        {id: 1, name: 'aa'},
        {id: 2, name: 'bb'},
        {id: 3, name: 'cc'},
    ]

    const getUserById = id =>
        find(u => u.id == id, users) || Promise.reject('없어요!')

    const f = ({name}) => name;
    const g = getUserById;


    // const fg = id => f(g(id));

    const fg = id => Promise.resolve(id).then(g).then(f);

    fg(2).then(log);


</script>

